# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50d3d3fec7ac8de11f6e55b97eb3699d4a58b9eec29ac97269828a1aaeb289638cd14f6c1d319c6bcae037c90ef2404ac5850df9d41cb98159ac59a8c9b35ad5

test:
  secret_key_base: 9c9812338d1c21f445960c18cdb992240369428f98a531ce11100d6a35c1cd26bfa1723bbacd56d91c0b6316e2f4c2fe3263618d2e7df2531c6cf25206c5fc89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
